### PR TITLE
fix "NoSuchBucket" error in local deployment with docker

### LINKED ISSUE #1859: validation problem with the docker installation
with the help of @Gregoor  i managed to install locally the project using the docker setup; recording is working but can not validate, the listen page show the audios but when i click on play button the audio is not stopping and i can only click the NO button and not the OK(button is disabled) to validate the recording.

Any help please.

### PR DESCRIPTION
**Pull request by a-oz**
Server store recordings in `CV_CLIP_BUCKET_NAME`, and the bucket create in s3proxy should have the same name, in this case `common-voice-clips`

This resolves #1859, #3009

### CODE REVIEW

File: docker/prepare_s3.sh [hunk 1]
```diff
@@ -2,14 +2,14 @@
 
 # Check if voice-web bucket exists if not create it
 echo "Checking if s3 bucket exists..."
-status=$(curl -XGET s3proxy/common-voice-corpus --write-out "%{http_code}\n" --output /dev/null --silent)
+status=$(curl -XGET s3proxy/common-voice-clips --write-out "%{http_code}\n" --output /dev/null --silent)
```
Comment (jarivk) [inline docker/prepare_s3.sh:5]: Instead of hardcoding bucket name here, should we take it from environment variable CV_CLIP_BUCKET_NAME  and set it in .env-local-docker ?

Comment (a-oz) [reply docker/prepare_s3.sh:5]: `CV_CLIP_BUCKET_NAME` is an item in `.env-local-docker`, it's an environment variable.

Comment (a-oz) [reply docker/prepare_s3.sh:5]: `CV_CLIP_BUCKET_NAME` is not an environment variable, it's an item in config file and not available to `docker/prepare_s3.sh`

Comment (a-oz) [reply docker/prepare_s3.sh:5]: A possible solution is to put in in `.env`, and compose will pick it up as a environment variable.

**Comment by phirework** [comment]
Hello! Thanks for submitting this PR. There's actually some other problems with the Docker config relating to race conditions and the s3proxy container not being ready yet when `prepare_s3.sh` tries to initialize that will be resolved in #3049, so if you're still running into S3 issues be sure to pull from main once that merges!
