### PR TITLE
fix(contribution-activity): all contribution doesnt work

### LINKED ISSUE #3465: [BUG] Statistics graphs on Dashboard not shown
**Describe the bug**
This also happened after the last update, although there are contributions, they are not shown on the grapth.
On the other hand, your own contributions are shown.

image

**To Reproduce**
1. Go to your dashboard
2. Click on "Everyone"

### PR DESCRIPTION
**Pull request by zaccolley**
Fixes #3465

The existing component was no longer remounting for some reason after refactoring, so I have rewritten it to be how it should have probably always been.

Added a test so doesn't happen again.

### CODE REVIEW

File: web/src/services/api.ts [hunk 1]
```diff
@@ -228,18 +228,14 @@ export default class API {
...
-    }[]
-  > {
-    return this.fetch(
-      API_PATH +
-        (locale ? '/' + locale : '') +
-        '/contribution_activity?from=' +
-        from
-    );
+  ): Promise<{ date: string; value: number }[]> {
+    let endpoint = API_PATH;
```
Comment (zaccolley) [inline web/src/services/api.ts:232]: This is style change, found the existing function very hard to read

File: web/src/components/pages/dashboard/stats/contribution-activity.tsx [hunk 2]
```diff
@@ -1,36 +1,23 @@
 import * as React from 'react';
```
Comment (zaccolley) [inline web/src/components/pages/dashboard/stats/contribution-activity.tsx:1]: Basically rewrote this. [Split diff view](?diff=split&w=1) is easier to see whats changed.

**Review by mozgzh — APPROVED** [review]

**Review by phirework — APPROVED** [review]
